#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        if command -v cygpath > /dev/null 2>&1; then
            basedir=`cygpath -w "$basedir"`
        fi
    ;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/Users/WIN-11/AppData/Local/pnpm/global/5/.pnpm/eas-cli@22.2.0_@types+node@26.2.0_typescript@5.9.3/node_modules/eas-cli/bin/node_modules:/mnt/c/Users/WIN-11/AppData/Local/pnpm/global/5/.pnpm/eas-cli@22.2.0_@types+node@26.2.0_typescript@5.9.3/node_modules/eas-cli/node_modules:/mnt/c/Users/WIN-11/AppData/Local/pnpm/global/5/.pnpm/eas-cli@22.2.0_@types+node@26.2.0_typescript@5.9.3/node_modules:/mnt/c/Users/WIN-11/AppData/Local/pnpm/global/5/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/Users/WIN-11/AppData/Local/pnpm/global/5/.pnpm/eas-cli@22.2.0_@types+node@26.2.0_typescript@5.9.3/node_modules/eas-cli/bin/node_modules:/mnt/c/Users/WIN-11/AppData/Local/pnpm/global/5/.pnpm/eas-cli@22.2.0_@types+node@26.2.0_typescript@5.9.3/node_modules/eas-cli/node_modules:/mnt/c/Users/WIN-11/AppData/Local/pnpm/global/5/.pnpm/eas-cli@22.2.0_@types+node@26.2.0_typescript@5.9.3/node_modules:/mnt/c/Users/WIN-11/AppData/Local/pnpm/global/5/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "C:/Users/WIN-11/AppData/Local/pnpm/global/5/.pnpm/eas-cli@22.2.0_@types+node@26.2.0_typescript@5.9.3/node_modules/eas-cli/bin/run" "$@"
else
  exec node  "C:/Users/WIN-11/AppData/Local/pnpm/global/5/.pnpm/eas-cli@22.2.0_@types+node@26.2.0_typescript@5.9.3/node_modules/eas-cli/bin/run" "$@"
fi
