import { Feather } from '@expo/vector-icons';

export interface CategoryInfo {
  id: string;
  slug: string;
  name: string;
  emoji: string;
  icon: keyof typeof Feather.glyphMap;
  color: string;
  bgColor: string;
  subcategories: string[];
}

export const EXPENSE_CATEGORIES: CategoryInfo[] = [
  {
    id: 'baby-children',
    slug: 'baby-children',
    name: 'Baby & Children',
    emoji: '👶',
    icon: 'smile',
    color: '#F472B6',
    bgColor: '#FDF2F8',
    subcategories: [
      'Baby Accessories',
      'Baby Clothes',
      'Baby Food',
      'Baby Medicine',
      'Child Care',
      'Diapers',
      'Other Baby & Children',
      'School Items',
      'Toys',
    ],
  },
  {
    id: 'bills-utilities',
    slug: 'bills-utilities',
    name: 'Bills & Utilities',
    emoji: '💡',
    icon: 'zap',
    color: '#EAB308',
    bgColor: '#FEF9C3',
    subcategories: [
      'Cable TV',
      'Electricity',
      'Garbage',
      'Gas',
      'Internet',
      'Mobile Bill',
      'Mobile Recharge',
      'Other Utilities',
      'Telephone',
      'Water',
    ],
  },
  {
    id: 'business',
    slug: 'business',
    name: 'Business',
    emoji: '🏢',
    icon: 'briefcase',
    color: '#4338CA',
    bgColor: '#E0E7FF',
    subcategories: [
      'Advertising',
      'API',
      'Business Equipment',
      'Business Meeting',
      'Business Travel',
      'Delivery',
      'Domain',
      'Employee Salary',
      'Hosting',
      'Inventory',
      'Marketing',
      'Office Rent',
      'Other Business',
      'Professional Membership',
      'Software',
      'Supplier Payment',
      'VPS',
    ],
  },
  {
    id: 'clothing-fashion',
    slug: 'clothing-fashion',
    name: 'Clothing & Fashion',
    emoji: '👕',
    icon: 'tag',
    color: '#C026D3',
    bgColor: '#FAE8FF',
    subcategories: [
      'Accessories',
      'Bag',
      'Clothes',
      'Dry Cleaning',
      'Jewelry',
      'Other Fashion',
      'Shoes',
      'Tailor',
      'Watch',
    ],
  },
  {
    id: 'delivery-courier',
    slug: 'delivery-courier',
    name: 'Delivery & Courier',
    emoji: '📮',
    icon: 'truck',
    color: '#EA580C',
    bgColor: '#FFEDD5',
    subcategories: [
      'Courier',
      'Delivery Charge',
      'Food Delivery',
      'Other Delivery',
      'Packaging',
      'Parcel',
      'Shipping',
    ],
  },
  {
    id: 'digital-payments',
    slug: 'digital-payments',
    name: 'Digital Payments',
    emoji: '💳',
    icon: 'credit-card',
    color: '#E11D48',
    bgColor: '#FFE4E6',
    subcategories: [
      'ATM Fee',
      'Bank Transfer Fee',
      'bKash Charge',
      'Nagad Charge',
      'Other Digital Payment',
      'Payment Gateway Fee',
      'Rocket Charge',
      'Transaction Fee',
    ],
  },
  {
    id: 'education',
    slug: 'education',
    name: 'Education',
    emoji: '📚',
    icon: 'book',
    color: '#0891B2',
    bgColor: '#CFFAFE',
    subcategories: [
      'Admission Fee',
      'Books',
      'Certification',
      'College Fee',
      'Course',
      'E-books',
      'Exam Fee',
      'Other Education',
      'Photocopy',
      'Printing',
      'School Fee',
      'Stationery',
      'Study Materials',
      'Training',
      'Tuition',
      'University Fee',
    ],
  },
  {
    id: 'emergency',
    slug: 'emergency',
    name: 'Emergency',
    emoji: '🚨',
    icon: 'alert-triangle',
    color: '#DC2626',
    bgColor: '#FEE2E2',
    subcategories: [
      'Emergency Family Support',
      'Emergency Medical',
      'Emergency Purchase',
      'Emergency Repair',
      'Emergency Travel',
      'Other Emergency',
    ],
  },
  {
    id: 'entertainment',
    slug: 'entertainment',
    name: 'Entertainment',
    emoji: '🎮',
    icon: 'film',
    color: '#8B5CF6',
    bgColor: '#EDE9FE',
    subcategories: [
      'Concert',
      'Events',
      'Games',
      'Gaming',
      'Hobbies',
      'Movies',
      'Music',
      'Other Entertainment',
      'Photography',
      'Sports',
      'Streaming',
    ],
  },
  {
    id: 'family',
    slug: 'family',
    name: 'Family',
    emoji: '👨‍👩‍👧',
    icon: 'users',
    color: '#F97316',
    bgColor: '#FFEDD5',
    subcategories: [
      'Children',
      'Family Education',
      'Family Food',
      'Family Gifts',
      'Family Medical',
      'Family Support',
      'Family Travel',
      'Other Family',
      'Parents',
      'Spouse',
    ],
  },
  {
    id: 'financial',
    slug: 'financial',
    name: 'Financial',
    emoji: '🏦',
    icon: 'dollar-sign',
    color: '#059669',
    bgColor: '#D1FAE5',
    subcategories: [
      'ATM Fee',
      'Bank Fee',
      'Credit Card Fee',
      'Credit Card Payment',
      'Insurance',
      'Interest',
      'Investment',
      'Loan Interest',
      'Loan Payment',
      'Other Financial',
      'Service Charge',
      'Tax',
    ],
  },
  {
    id: 'food-dining',
    slug: 'food-dining',
    name: 'Food & Dining',
    emoji: '🍛',
    icon: 'coffee',
    color: '#D97706',
    bgColor: '#FEF3C7',
    subcategories: [
      'Bakery',
      'Chicken',
      'Dessert',
      'Eggs',
      'Energy Drinks',
      'Fast Food',
      'Fish',
      'Food Delivery',
      'Fruits',
      'Groceries',
      'Ice Cream',
      'Juice',
      'Meat',
      'Milk & Dairy',
      'Other Food',
      'Restaurant',
      'Rice',
      'Snacks',
      'Soft Drinks',
      'Street Food',
      'Tea/Coffee',
      'Vegetables',
      'Water',
    ],
  },
  {
    id: 'freelance-professional',
    slug: 'freelance-professional',
    name: 'Freelance & Professional',
    emoji: '💻',
    icon: 'code',
    color: '#7C3AED',
    bgColor: '#EDE9FE',
    subcategories: [
      'API',
      'Client Meeting',
      'Domain',
      'Freelance Platform Fee',
      'Hosting',
      'Other Professional',
      'Professional Membership',
      'Professional Tools',
      'Software License',
      'VPS',
      'Work Equipment',
    ],
  },
  {
    id: 'gifts-donation',
    slug: 'gifts-donation',
    name: 'Gifts & Donation',
    emoji: '🎁',
    icon: 'gift',
    color: '#D946EF',
    bgColor: '#FAE8FF',
    subcategories: [
      'Birthday Gift',
      'Charity',
      'Donation',
      'Fitra',
      'Gift',
      'Other Donation',
      'Qurbani',
      'Religious Giving',
      'Wedding Gift',
      'Zakat',
    ],
  },
  {
    id: 'government-legal',
    slug: 'government-legal',
    name: 'Government & Legal',
    emoji: '🏛️',
    icon: 'file-text',
    color: '#64748B',
    bgColor: '#F1F5F9',
    subcategories: [
      'Court Fee',
      'Document',
      'Driving License',
      'Government Fee',
      'Legal Service',
      'License',
      'NID Related',
      'Notary',
      'Other Government & Legal',
      'Passport',
      'Visa',
    ],
  },
  {
    id: 'health',
    slug: 'health',
    name: 'Health',
    emoji: '💊',
    icon: 'activity',
    color: '#EF4444',
    bgColor: '#FEE2E2',
    subcategories: [
      'Dental',
      'Doctor',
      'Emergency',
      'Eye Care',
      'Fitness',
      'Gym',
      'Health Insurance',
      'Hospital',
      'Medical Tests',
      'Medicine',
      'Mental Health',
      'Other Health',
      'Physiotherapy',
    ],
  },
  {
    id: 'household',
    slug: 'household',
    name: 'Household',
    emoji: '🧹',
    icon: 'home',
    color: '#16A34A',
    bgColor: '#DCFCE7',
    subcategories: [
      'Cleaning Supplies',
      'Dishwashing',
      'Gas Cylinder',
      'Home Essentials',
      'House Cleaner',
      'Kitchen Supplies',
      'Laundry',
      'Other Household',
      'Washing',
    ],
  },
  {
    id: 'housing',
    slug: 'housing',
    name: 'Housing',
    emoji: '🏠',
    icon: 'home',
    color: '#0284C7',
    bgColor: '#E0F2FE',
    subcategories: [
      'Cleaning',
      'Cleaning Supplies',
      'Furniture',
      'Home Appliance',
      'Home Decor',
      'House Maintenance',
      'Moving',
      'Other Housing',
      'Pest Control',
      'Rent',
      'Security',
    ],
  },
  {
    id: 'media-creative',
    slug: 'media-creative',
    name: 'Media & Creative',
    emoji: '📸',
    icon: 'camera',
    color: '#BE185D',
    bgColor: '#FCE7F3',
    subcategories: [
      'Design',
      'Editing',
      'Other Creative',
      'Photo Print',
      'Photography',
      'Printing',
      'Printing Materials',
      'Studio',
      'Videography',
    ],
  },
  {
    id: 'others',
    slug: 'others',
    name: 'Others',
    emoji: '📦',
    icon: 'package',
    color: '#6B7280',
    bgColor: '#F3F4F6',
    subcategories: ['Miscellaneous', 'Other', 'Unknown'],
  },
  {
    id: 'personal-care',
    slug: 'personal-care',
    name: 'Personal Care',
    emoji: '💄',
    icon: 'smile',
    color: '#F43F5E',
    bgColor: '#FFE4E6',
    subcategories: [
      'Cosmetics',
      'Grooming',
      'Haircut',
      'Other Personal Care',
      'Perfume',
      'Personal Hygiene',
      'Salon',
      'Shaving',
      'Skincare',
      'Toiletries',
    ],
  },
  {
    id: 'pets',
    slug: 'pets',
    name: 'Pets',
    emoji: '🐶',
    icon: 'gitlab',
    color: '#A855F7',
    bgColor: '#F3E8FF',
    subcategories: [
      'Other Pets',
      'Pet Accessories',
      'Pet Food',
      'Pet Grooming',
      'Pet Insurance',
      'Pet Medicine',
      'Pet Toys',
      'Pet Training',
      'Veterinary',
    ],
  },
  {
    id: 'property',
    slug: 'property',
    name: 'Property',
    emoji: '🏡',
    icon: 'home',
    color: '#0D9488',
    bgColor: '#CCFBF1',
    subcategories: [
      'Construction',
      'Other Property',
      'Property Maintenance',
      'Property Management',
      'Property Purchase',
      'Property Rent',
      'Property Tax',
      'Renovation',
      'Repair',
    ],
  },
  {
    id: 'religious',
    slug: 'religious',
    name: 'Religious',
    emoji: '🕌',
    icon: 'heart',
    color: '#14B8A6',
    bgColor: '#CCFBF1',
    subcategories: [
      'Fitra',
      'Hajj',
      'Islamic Books',
      'Mosque Donation',
      'Other Religious',
      'Qurbani',
      'Quran',
      'Religious Clothing',
      'Religious Event',
      'Umrah',
      'Zakat',
    ],
  },
  {
    id: 'repair-maintenance',
    slug: 'repair-maintenance',
    name: 'Repair & Maintenance',
    emoji: '🔧',
    icon: 'tool',
    color: '#71717A',
    bgColor: '#F4F4F5',
    subcategories: [
      'AC Repair',
      'Appliance Repair',
      'Bike Repair',
      'Car Repair',
      'Computer Repair',
      'Electrical Repair',
      'Home Repair',
      'Laptop Repair',
      'Mobile Repair',
      'Other Repair',
      'Plumbing',
    ],
  },
  {
    id: 'savings',
    slug: 'savings',
    name: 'Savings',
    emoji: '💰',
    icon: 'shield',
    color: '#10B981',
    bgColor: '#D1FAE5',
    subcategories: [
      'DPS',
      'Education Fund',
      'Emergency Fund',
      'FDR',
      'Future Purchase',
      'General Savings',
      'House Fund',
      'Other Savings',
      'Retirement',
      'Travel Fund',
    ],
  },
  {
    id: 'shopping',
    slug: 'shopping',
    name: 'Shopping',
    emoji: '🛍️',
    icon: 'shopping-bag',
    color: '#EC4899',
    bgColor: '#FCE7F3',
    subcategories: [
      'Accessories',
      'Bag',
      'Clothes',
      'Computer',
      'Electronics',
      'Home Items',
      'Jewelry',
      'Kitchen Items',
      'Mobile Phone',
      'Online Shopping',
      'Other Shopping',
      'Personal Items',
      'Shoes',
      'Stationery',
      'Watch',
    ],
  },
  {
    id: 'smoking-tobacco',
    slug: 'smoking-tobacco',
    name: 'Smoking & Tobacco',
    emoji: '🚬',
    icon: 'wind',
    color: '#78716C',
    bgColor: '#F5F5F4',
    subcategories: [
      'Cigar',
      'Cigarettes',
      'Other Tobacco',
      'Smoking Accessories',
      'Tobacco',
      'Vape',
    ],
  },
  {
    id: 'sports-fitness',
    slug: 'sports-fitness',
    name: 'Sports & Fitness',
    emoji: '🏋️',
    icon: 'award',
    color: '#2563EB',
    bgColor: '#DBEAFE',
    subcategories: [
      'Badminton',
      'Cricket',
      'Cycling',
      'Football',
      'Gym',
      'Other Sports',
      'Running',
      'Sports Club',
      'Sports Equipment',
      'Swimming',
    ],
  },
  {
    id: 'student',
    slug: 'student',
    name: 'Student',
    emoji: '🎓',
    icon: 'book-open',
    color: '#1D4ED8',
    bgColor: '#DBEAFE',
    subcategories: [
      'Admission',
      'Books',
      'Exam',
      'Hostel',
      'Mess',
      'Other Student',
      'Photocopy',
      'Printing',
      'Semester Fee',
      'Student Transport',
      'Study Materials',
      'Tuition',
    ],
  },
  {
    id: 'subscriptions',
    slug: 'subscriptions',
    name: 'Subscriptions',
    emoji: '📱',
    icon: 'tv',
    color: '#6366F1',
    bgColor: '#EEF2FF',
    subcategories: [
      'AI Subscription',
      'Amazon Prime',
      'Apple Services',
      'Cloud Storage',
      'Gaming Subscription',
      'Google Services',
      'Netflix',
      'News Subscription',
      'Other Subscription',
      'Software',
      'Spotify',
      'YouTube',
    ],
  },
  {
    id: 'taxes',
    slug: 'taxes',
    name: 'Taxes',
    emoji: '🧾',
    icon: 'file-text',
    color: '#475569',
    bgColor: '#F1F5F9',
    subcategories: [
      'Government Tax',
      'Income Tax',
      'Municipal Tax',
      'Other Tax',
      'Property Tax',
      'Tax Filing Fee',
      'VAT',
    ],
  },
  {
    id: 'transport',
    slug: 'transport',
    name: 'Transport',
    emoji: '🚗',
    icon: 'navigation',
    color: '#2563EB',
    bgColor: '#DBEAFE',
    subcategories: [
      'Auto Rickshaw',
      'Bike Maintenance',
      'Bus',
      'Car Maintenance',
      'CNG',
      'Driving License',
      'Fuel',
      'Other Transport',
      'Parking',
      'Rickshaw',
      'Ride Share',
      'Taxi',
      'Toll',
      'Train',
      'Vehicle Insurance',
      'Vehicle Maintenance',
      'Vehicle Registration',
      'Vehicle Repair',
    ],
  },
  {
    id: 'travel',
    slug: 'travel',
    name: 'Travel',
    emoji: '✈️',
    icon: 'map-pin',
    color: '#06B6D4',
    bgColor: '#E0F2FE',
    subcategories: [
      'Activities',
      'Food',
      'Guest House',
      'Hostel',
      'Hotel',
      'Other Travel',
      'Passport',
      'Souvenirs',
      'Tickets',
      'Tour',
      'Tour Guide',
      'Transport',
      'Travel Insurance',
      'Visa',
    ],
  },
  {
    id: 'work',
    slug: 'work',
    name: 'Work',
    emoji: '💼',
    icon: 'briefcase',
    color: '#3B82F6',
    bgColor: '#DBEAFE',
    subcategories: [
      'Business Meeting',
      'Equipment',
      'Office Lunch',
      'Office Supplies',
      'Office Transport',
      'Other Work',
      'Professional Fees',
      'Software',
      'Training',
      'Work Clothing',
      'Work Internet',
      'Work Travel',
    ],
  },
];

export const SPLIT_TYPES = {
  EQUAL: 'EQUAL',
  EXACT: 'EXACT',
  PERCENTAGE: 'PERCENTAGE',
  SHARES: 'SHARES',
} as const;

export type SplitType = keyof typeof SPLIT_TYPES;
